### ISSUE TITLE
Localization on-line

### ISSUE THREAD

**Issue by ucmmesa** [xdspacelab/openvslam#16]
Thanks for sharing your great work!
I am puzzled how to locate a real moving platform on-line after building the field map?

**Comment by shinsumicco** [comment]
Could you refer to [`./example/run_image_slam.cc#L46`](https://github.com/xdspacelab/openvslam/blob/master/example/run_image_slam.cc#L64)?
Please pass a real-time image frame by calling `track_for_monocular()` sequentially instead of inputting images which stored in a storage to it.
This function returns an estimated camera pose of a input frame.

**Comment by rahuldeo2047** [comment]
Ref only: https://github.com/xdspacelab/openvslam/issues/157
