### ISSUE TITLE
Run_video_slam.exe stop half way.

### ISSUE THREAD

**Issue by michealChin** [xdspacelab/openvslam#221]
![vslam](https://user-images.githubusercontent.com/12890191/72126201-3c735300-33a6-11ea-8ddd-fd87bbe811d7.png)

I am able to build and run the sample Run_video_slam.exe, but after run a few frames a debug assertion warning message popup. The warning message is attached with this issue.

**Comment by reunanen** [comment]
How did you build? Using [this](https://github.com/reunanen/openvslam-build-vs)?

**Comment by michealChin** [comment]
Yup, I follow the instruction exactly. Thanks for your great effort to convert it into vs project!

**Comment by reunanen** [comment]
Oh, actually I _can_ reproduce this! I thought I couldn't but previously I just didn't wait long enough.

**Comment by reunanen** [comment]
Should be fixed now. Just pull the latest [openvslam-build-vs](https://github.com/reunanen/openvslam-build-vs) and update the submodule (`git submodule update`).

**Comment by reunanen** [comment]
(Or alternatively, cherry-pick [c04bfa09](https://github.com/reunanen/openvslam/commit/c04bfa09de5efe3f099ee31aa166629bd70e81db).)

**Comment by reunanen** [comment]
@shinsumicco As suggested by [the bug report](https://github.com/xdspacelab/openvslam/issues/221#issue-547862411), this problem can be reproduced by running a Debug build in Visual Studio. (But as I [wrote already](
https://github.com/xdspacelab/openvslam/pull/217#discussion_r365566656), I believe this bug is more general, i.e. not really specific to Visual Studio or Windows.)
