### ISSUE TITLE
SLAM System reset BUG

### ISSUE THREAD

**Issue by SKioresku** [xdspacelab/openvslam#323]
![Безымянный](https://user-images.githubusercontent.com/18395805/82322241-deebb480-99de-11ea-9a43-179983137775.png)

I am find up, that that sign can be incorrect.

**Comment by dimaxano** [comment]
What sign do you think should be there?

**Comment by shinsumicco** [comment]
The conditions of the `if` statement control a reset of the system when tracking is lost within `init_retry_thr` (sec/secs) after the initialization.
So the second condition is correct because **(CURRENT_FRAME_ID - INITIAL_FRAME_ID) / FPS** equals to the elapsed time after the initialization except when frames are skipped.

**Comment by SKioresku** [comment]
Now in the developer code system going to reset instantly after Lost state. You can test that.

**Comment by SKioresku** [comment]
> What sign do you think should be there?

curr_frm_.id_ - initializer_.get_initial_frame_id() > camera_->fps_ * init_retry_thr

**Comment by dimaxano** [comment]
Well, according to your variant system should reset if tracking is LOST and it passed more than `init_retry_thr` seconds from tracking start
Am I right?

**Comment by SKioresku** [comment]
> Well, according to your variant system should reset if tracking is LOST and it passed more than `init_retry_thr` seconds from tracking start
> Am I right?

Stop... Now i see that reset system goes if passed less then 5.0 sec after INITIALIZATION (not from the last succed tracking). Now it makes sence.
