### ISSUE TITLE
Integrate pose from external sensor into OpenVSLAM when tracking is LOST

### ISSUE THREAD

**Issue by dimaxano** [xdspacelab/openvslam#367]
Hi! 
While using openvslam on my robot, I have **a)** local position (based on GPS and IMU) estimated by autopilot software and **b)** transformation from autopilot local frame to slam frame.
I want to make use of it when tracking is LOST by telling openvslam after reinitialization its real position on the map, instead of (0,0,0) it would obtain after reinitialization.

For now I see solution to be the next:
1. Tracking is LOST, we are NOT resetting the system (except `initializer_`) and waiting for the next successful initialization.
2. When successful initialization (`try_initialize_for_monocular` returned True) happened, I just put corresponding position from my autopilot [here](https://github.com/xdspacelab/openvslam/blob/6de5fec058647297ca3458e4719b42947fd4a582/src/openvslam/module/initializer.cc#L175) and [here](https://github.com/xdspacelab/openvslam/blob/6de5fec058647297ca3458e4719b42947fd4a582/src/openvslam/module/initializer.cc#L179) instead of calculated one.

Am I missing something? Would appreciate any piece of advice

**Comment by YujiElfahkrany** [comment]
@dimaxano I think the problem is how to get openvslam to build on this input. 
for example [here](https://github.com/xdspacelab/openvslam/blob/6de5fec058647297ca3458e4719b42947fd4a582/src/openvslam/tracking_module.cc#L306) uses the lastframe pose to update the motionmodel. 

I guess every time we will have to calculate pose like this camera global pose = initialIMUinput * cw.inverse() ??
