### ISSUE TITLE
Installation for Windows 10

### ISSUE THREAD

**Issue by hetareba** [xdspacelab/openvslam#374]
I tried to install it by referring to Mr. Reunanen's explanation.
But I'm new to building software so I can't understand what I have to build with Visual Studio 2017.
Can anyone please tell me step by step?
I know
![openvslam - Microsoft Visual Studio  2020_06_27 14_42_56 (2)](https://user-images.githubusercontent.com/63937056/85915772-4d951b00-b885-11ea-9197-6842fd38b7e5.png)
 this is a very annoying request, but I need your help.
I have already tried every method...

(What I should do next? :< )

Reference: [https://github.com/reunanen/openvslam-build-vs](url)

**Comment by shinsumicco** [comment]
@hetareba Thank you for having the interest on this project.
I'm sorry that we've not actually tried the instructions posted by @reunanen for building OpenVSLAM on Windows environment.
But I provide PowerShell scripts [here](https://github.com/shinsumicco/openvslam-on-msvc) in order to make MSVC project from the CMake scripts.
If you accept this way for your purpose, could you try those scripts?

**Comment by hetareba** [comment]
Thanks a lot!!! I'll try it soon, then i'll report the result.

**Comment by reunanen** [comment]
@hetareba One way to build a specific project is to use the "Solution Explorer" (see bottom left in the image below), right-click the desired project, and choose "Build".

![image](https://user-images.githubusercontent.com/2297572/85929882-eac17500-b8c0-11ea-9e50-38848c8e17ce.png)

**Comment by hetareba** [comment]
![messageImage_1593394304776](https://user-images.githubusercontent.com/63937056/85964274-f9f50f80-b9f3-11ea-988f-c990abb01ab5.jpg)

Thank you everyone for your cooperation.
The build was successful.
And the attached screenshots show that the tutorial was successful.
As you can see, I ended up using Ubuntu.
But success could not have been possible without your cooperation.
Thank you very much 👍 .
